# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-17 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picurl',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
